---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: rest-villain
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: rest-villain
spec:
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  selector:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: openjdk-11-rhel7
spec:
  dockerImageRepository: registry.access.redhat.com/openjdk/openjdk-11-rhel7
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: rest-villain
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: rest-villain
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rest-villain:01
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11-rhel7:latest
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: rest-villain
spec:
  replicas: 3
  selector:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
  template:
    metadata:
      annotations:
        prometheus.io/port: "8084"
        app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
        app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
        app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
        app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/name: rest-villain
        app.kubernetes.io/version: "01"
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_JAR
          value: /deployments/rest-villain-01-runner.jar
        - name: JAVA_LIB_DIR
          value: /deployments/lib
        - name: JAVA_CLASSPATH
          value: /deployments/lib/io.quarkus.quarkus-security-runtime-spi-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-development-mode-spi-1.7.2.Final.jar:/deployments/lib/org.reactivestreams.reactive-streams-1.0.3.jar:/deployments/lib/io.smallrye.reactive.mutiny-0.7.0.jar:/deployments/lib/io.quarkus.security.quarkus-security-1.1.2.Final.jar:/deployments/lib/jakarta.el.jakarta.el-api-3.0.3.jar:/deployments/lib/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:/deployments/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:/deployments/lib/io.netty.netty-codec-4.1.49.Final.jar:/deployments/lib/io.netty.netty-handler-4.1.49.Final.jar:/deployments/lib/io.quarkus.quarkus-netty-1.7.2.Final.jar:/deployments/lib/io.netty.netty-common-4.1.49.Final.jar:/deployments/lib/io.netty.netty-buffer-4.1.49.Final.jar:/deployments/lib/io.netty.netty-transport-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-socks-4.1.49.Final.jar:/deployments/lib/io.netty.netty-handler-proxy-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-http-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-http2-4.1.49.Final.jar:/deployments/lib/io.netty.netty-resolver-4.1.49.Final.jar:/deployments/lib/io.netty.netty-codec-dns-4.1.49.Final.jar:/deployments/lib/io.netty.netty-resolver-dns-4.1.49.Final.jar:/deployments/lib/io.vertx.vertx-core-3.9.2.jar:/deployments/lib/io.quarkus.quarkus-vertx-core-1.7.2.Final.jar:/deployments/lib/io.vertx.vertx-web-common-3.9.2.jar:/deployments/lib/io.vertx.vertx-auth-common-3.9.2.jar:/deployments/lib/io.vertx.vertx-bridge-common-3.9.2.jar:/deployments/lib/io.vertx.vertx-web-3.9.2.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-1.7.2.Final.jar:/deployments/lib/org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-spi-4.5.6.Final.jar:/deployments/lib/com.ibm.async.asyncutil-0.1.0.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-4.5.6.Final.jar:/deployments/lib/com.sun.activation.jakarta.activation-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-resteasy-common-1.7.2.Final.jar:/deployments/lib/jakarta.validation.jakarta.validation-api-2.0.2.jar:/deployments/lib/io.quarkus.quarkus-resteasy-server-common-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-1.7.2.Final.jar:/deployments/lib/org.eclipse.yasson-1.0.8.jar:/deployments/lib/io.quarkus.quarkus-jsonb-1.7.2.Final.jar:/deployments/lib/org.glassfish.jakarta.json-1.1.6.jar:/deployments/lib/jakarta.json.bind.jakarta.json.bind-api-1.0.2.jar:/deployments/lib/org.jboss.logging.jboss-logging-3.3.2.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-json-binding-provider-4.5.6.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-json-p-provider-4.5.6.Final.jar:/deployments/lib/commons-io.commons-io-2.7.jar:/deployments/lib/io.quarkus.quarkus-resteasy-jsonb-1.7.2.Final.jar:/deployments/lib/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:/deployments/lib/io.smallrye.common.smallrye-common-annotation-1.1.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-common-1.8.5.jar:/deployments/lib/io.smallrye.common.smallrye-common-function-1.1.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-expression-1.1.0.jar:/deployments/lib/io.smallrye.common.smallrye-common-constraint-1.1.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-1.8.5.jar:/deployments/lib/org.jboss.logmanager.jboss-logmanager-embedded-1.0.4.jar:/deployments/lib/org.jboss.logging.jboss-logging-annotations-2.1.0.Final.jar:/deployments/lib/org.jboss.threads.jboss-threads-3.1.1.Final.jar:/deployments/lib/org.slf4j.slf4j-api-1.7.30.jar:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logging-1.2.0.Final.jar:/deployments/lib/org.graalvm.sdk.graal-sdk-20.1.0.jar:/deployments/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/deployments/lib/io.quarkus.quarkus-bootstrap-runner-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-core-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-datasource-common-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-datasource-1.7.2.Final.jar:/deployments/lib/org.jboss.jboss-transaction-spi-7.6.0.Final.jar:/deployments/lib/org.jboss.spec.javax.resource.jboss-connector-api_1.7_spec-1.0.0.Final.jar:/deployments/lib/org.jboss.narayana.jta.narayana-jta-5.10.5.Final.jar:/deployments/lib/org.jboss.narayana.jts.narayana-jts-integration-5.10.5.Final.jar:/deployments/lib/io.agroal.agroal-api-1.8.jar:/deployments/lib/io.agroal.agroal-narayana-1.8.jar:/deployments/lib/io.agroal.agroal-pool-1.8.jar:/deployments/lib/io.quarkus.quarkus-credentials-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-agroal-1.7.2.Final.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-api-1.0.13.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-1.0.13.jar:/deployments/lib/io.quarkus.quarkus-smallrye-context-propagation-1.7.2.Final.jar:/deployments/lib/io.smallrye.reactive.mutiny-context-propagation-0.7.0.jar:/deployments/lib/io.quarkus.quarkus-mutiny-1.7.2.Final.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-jta-1.0.13.jar:/deployments/lib/io.smallrye.reactive.smallrye-reactive-converter-api-1.1.0.jar:/deployments/lib/io.smallrye.reactive.smallrye-reactive-converter-mutiny-1.1.0.jar:/deployments/lib/io.quarkus.quarkus-narayana-jta-1.7.2.Final.jar:/deployments/lib/net.bytebuddy.byte-buddy-1.10.10.jar:/deployments/lib/antlr.antlr-2.7.7.jar:/deployments/lib/org.dom4j.dom4j-2.1.3.jar:/deployments/lib/org.hibernate.common.hibernate-commons-annotations-5.1.0.Final.jar:/deployments/lib/org.hibernate.hibernate-core-5.4.21.Final.jar:/deployments/lib/org.hibernate.hibernate-graalvm-5.4.21.Final.jar:/deployments/lib/org.glassfish.jaxb.txw2-2.3.3-b02.jar:/deployments/lib/com.sun.istack.istack-commons-runtime-3.0.10.jar:/deployments/lib/org.glassfish.jaxb.jaxb-runtime-2.3.3-b02.jar:/deployments/lib/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:/deployments/lib/jakarta.persistence.jakarta.persistence-api-2.2.3.jar:/deployments/lib/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:/deployments/lib/com.google.errorprone.error_prone_annotations-2.2.0.jar:/deployments/lib/com.github.ben-manes.caffeine.caffeine-2.8.5.jar:/deployments/lib/org.hibernate.quarkus-local-cache-0.1.0.jar:/deployments/lib/io.quarkus.quarkus-caffeine-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-hibernate-orm-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-hibernate-orm-panache-common-1.7.2.Final.jar:/deployments/lib/io.quarkus.arc.arc-1.7.2.Final.jar:/deployments/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.0.1.jar:/deployments/lib/io.quarkus.quarkus-arc-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-panache-common-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-hibernate-orm-panache-1.7.2.Final.jar:/deployments/lib/org.postgresql.postgresql-42.2.14.jar:/deployments/lib/io.quarkus.quarkus-jdbc-postgresql-1.7.2.Final.jar:/deployments/lib/com.fasterxml.classmate-1.3.4.jar:/deployments/lib/org.hibernate.validator.hibernate-validator-6.1.5.Final.jar:/deployments/lib/org.glassfish.jakarta.el-3.0.3.jar:/deployments/lib/io.quarkus.quarkus-hibernate-validator-1.7.2.Final.jar:/deployments/lib/org.eclipse.microprofile.openapi.microprofile-openapi-api-1.1.2.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-core-2.11.2.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-annotations-2.11.2.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-databind-2.11.2.jar:/deployments/lib/org.yaml.snakeyaml-1.26.jar:/deployments/lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.11.2.jar:/deployments/lib/org.jboss.jandex-2.2.1.Final.jar:/deployments/lib/io.smallrye.smallrye-open-api-core-2.0.7.jar:/deployments/lib/io.quarkus.quarkus-swagger-ui-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-smallrye-openapi-1.7.2.Final.jar:/deployments/lib/org.eclipse.microprofile.health.microprofile-health-api-2.2.jar:/deployments/lib/io.smallrye.smallrye-health-api-2.2.3.jar:/deployments/lib/io.smallrye.smallrye-health-2.2.3.jar:/deployments/lib/io.smallrye.smallrye-health-ui-2.2.3.jar:/deployments/lib/io.smallrye.smallrye-health-provided-checks-2.2.3.jar:/deployments/lib/io.quarkus.quarkus-jsonp-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-smallrye-health-1.7.2.Final.jar:/deployments/lib/io.smallrye.smallrye-metrics-2.4.3.jar:/deployments/lib/org.eclipse.microprofile.metrics.microprofile-metrics-api-2.3.jar:/deployments/lib/io.quarkus.quarkus-smallrye-metrics-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-kubernetes-client-internal-1.7.2.Final.jar:/deployments/lib/io.quarkus.quarkus-openshift-1.7.2.Final.jar:/deployments/lib/org.eclipse.microprofile.config.microprofile-config-api-1.4.jar:/deployments/lib/org.eclipse.microprofile.opentracing.microprofile-opentracing-api-1.3.3.jar:/deployments/lib/org.eclipse.microprofile.rest.client.microprofile-rest-client-api-1.4.1.jar:/deployments/lib/io.opentracing.opentracing-api-0.31.0.jar:/deployments/lib/io.opentracing.opentracing-noop-0.31.0.jar:/deployments/lib/io.opentracing.contrib.opentracing-web-servlet-filter-0.2.3.jar:/deployments/lib/io.opentracing.contrib.opentracing-concurrent-0.2.0.jar:/deployments/lib/io.opentracing.contrib.opentracing-jaxrs2-0.4.1.jar:/deployments/lib/io.opentracing.contrib.opentracing-tracerresolver-0.1.8.jar:/deployments/lib/io.opentracing.contrib.opentracing-interceptors-0.0.4.jar:/deployments/lib/io.smallrye.smallrye-opentracing-1.3.4.jar:/deployments/lib/io.smallrye.smallrye-fault-tolerance-tracing-propagation-4.3.0.jar:/deployments/lib/jakarta.inject.jakarta.inject-api-1.0.jar:/deployments/lib/io.opentracing.opentracing-util-0.31.0.jar:/deployments/lib/com.google.code.gson.gson-2.8.6.jar:/deployments/lib/io.jaegertracing.jaeger-core-0.34.3.jar:/deployments/lib/org.apache.thrift.libthrift-0.13.0.jar:/deployments/lib/com.squareup.okio.okio-1.17.2.jar:/deployments/lib/com.squareup.okhttp3.okhttp-3.14.9.jar:/deployments/lib/io.jaegertracing.jaeger-thrift-0.34.3.jar:/deployments/lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-jaeger-1.7.2.Final.jar:/deployments/lib/jakarta.servlet.jakarta.servlet-api-4.0.3.jar:/deployments/lib/io.quarkus.quarkus-smallrye-opentracing-1.7.2.Final.jar:/deployments/lib/com.h2database.h2-1.4.197.jar:/deployments/lib/org.locationtech.jts.jts-core-1.15.0.jar:/deployments/lib/io.quarkus.quarkus-jdbc-h2-1.7.2.Final.jar
        - name: JAVA_OPTIONS
          value: -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        envFrom:
        - secretRef:
            name: villain-secret
        - configMapRef:
            name: villain-config
        image: user/rest-villain:01
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8084
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: rest-villain
        ports:
        - containerPort: 8084
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8084
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: rest-villain
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - rest-villain
      from:
        kind: ImageStreamTag
        name: rest-villain:01
    type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    prometheus.io/port: "8084"
    app.openshift.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/commit-id: 689c73f2946b3455da2652bf3bdc1c9000800548
    app.quarkus.io/vcs-url: https://github.com/gerasolis/bbva_ninja.git
    app.quarkus.io/build-timestamp: 2020-10-02 - 20:25:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
  labels:
    app.kubernetes.io/name: rest-villain
    app.kubernetes.io/version: "01"
    app.openshift.io/runtime: quarkus
  name: rest-villain
spec:
  host: ""
  path: /
  port:
    targetPort: 8084
  to:
    kind: Service
    name: rest-villain
